### ISSUE TITLE
Read Java's String api

### ISSUE THREAD

**Issue by thebhushanp** [shwetap1995/java_practise-#10]
Read this link till the end.
https://www.tutorialspoint.com/java/java_strings.htm

**Comment by thebhushanp** [comment]
Once you finish the reading, I will give assignment on String manipulation.

**Comment by shwetap1995** [comment]
The reading is over

**Comment by thebhushanp** [comment]
Test

**Comment by thebhushanp** [comment]
**Exercise** 
1. Take user's name as input and find the lenght of user's name
2. Take user's first and last name and print the combination of two separated by space on console.
3. Take user's name as input and his/her gender & marital status, and based on the inputs, print name with Mr, Miss or Ms
4. Take User's full name in following format,
"firstname middlename lastname" and print it in following format
First Name:
Middle Name:
Surname: 
5. Take user's name as a input and Print the user's name in Upper and lower case.
