### ISSUE TITLE
Not capturing gender information from user

### ISSUE THREAD

**Issue by thebhushanp** [shwetap1995/java_practise-#11]
https://github.com/shwetap1995/java_practise-/blob/8b982fa57b1ef4a12ca1f802dae264b091a6b9e5/problem11/PersonsDetails.java#L11

Read the problem definition carefully. 
You need ask for gender from user and based on that information, you need decide what to print. ie either Miss or Mr or Ms.

**Comment by shwetap1995** [comment]
issue solved
