### ISSUE TITLE
Use meaningful variable name

### ISSUE THREAD

**Issue by thebhushanp** [shwetap1995/java_practise-#3]
https://github.com/shwetap1995/java_practise-/blob/94bfd10810c041d5425bd0b773e38bdcd6d0278c/problem1/printnumbers.java#L4

You should have used <code>count</code> instead of <code>i</code>.

**Comment by thebhushanp** [comment]
Read [this](http://www.oracle.com/technetwork/java/codeconventions-135099.html#15429)

**Comment by shwetap1995** [comment]
All programs have taken a meaningful name
