### ISSUE TITLE
Code is not properly formatted

### ISSUE THREAD

**Issue by thebhushanp** [shwetap1995/java_practise-#4]
https://github.com/shwetap1995/java_practise-/blob/94bfd10810c041d5425bd0b773e38bdcd6d0278c/problem1/printnumbers.java#L6
Formatted code looks like below.
```
class printnumbers {
	public static void main(String args[]) {
		for (int i = 1; i <= 100; i++) {
			System.out.print(i + "\t");
		}
	}
  }
```

Such code is more readable as compare to unformatted code.

**Comment by shwetap1995** [comment]
code is now in proper format
