### ISSUE TITLE
Ticket concession program

### ISSUE THREAD

**Issue by thebhushanp** [shwetap1995/java_practise-#7]
Write a ticket concession program, which will take
**Input** as Age & Distance(KM)
**Output** Ticket price

Business Logic

1. There is will be 2.5 Rs/KM.
2. If age is less than 3 years then charge nothing.
3. If age is more than 3 years and less than 8 years then charge half.
4. If age is more than 60 years then charge half.

**Comment by shwetap1995** [comment]
done
